### ISSUE TITLE
add explanation to README on how to use Termonad from nixpkgs

### ISSUE THREAD

**Issue by asheshambasta** [cdepillabout/termonad#128]
(_edit from @cdepillabout_: This issue was about difficulty using Termonad from nixpkgs.  I think the main cause of this is that there is no explanation in the Termonad README of how to effectively use Termonad from nixpkgs.  Currently, the README only explains how to use Termonad when compiling from this repo.  An explanation of how to use Termonad directly from nixpkgs should be added to the README.)

-------------------------------------------------------------------------------------------------

When I add: 
- `termonad-with-packages`

```╰─$ termonad 
Configuration '/home/ashesh/.config/termonad/termonad.hs' changed. Recompiling.
Error occurred while loading configuration file.


/home/ashesh/.config/termonad/termonad.hs:21:51: error:
    Module ‘Termonad.Config.Colour’ does not export ‘AlphaColour’
   |
21 | import           Termonad.Config.Colour         ( AlphaColour
   |                                                   ^^^^^^^^^^^

/home/ashesh/.config/termonad/termonad.hs:24:51: error:
    Module ‘Termonad.Config.Colour’ does not export ‘createColour’
   |
24 |                                                 , createColour
   |                                                   ^^^^^^^^^^^^
```

--- 

When I add:
- `haskellPackages.termonad` 

```Configuration '/home/ashesh/.config/termonad/termonad.hs' changed. Recompiling.
Error occurred while loading configuration file.


/home/ashesh/.config/termonad/termonad.hs:5:1: error:
    Could not find module ‘Termonad.App’
    Use -v to see a list of the files searched for.
  |
5 | import           Termonad.App                   ( defaultMain )
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/home/ashesh/.config/termonad/termonad.hs:6:1: error:
    Could not find module ‘Termonad.Config’
    Perhaps you meant XMonad.Config (from xmonad-0.15)
    Use -v to see a list of the files searched for.
  |
6 | import           Termonad.Config                ( FontConfig
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

/home/ashesh/.config/termonad/termonad.hs:21:1: error:
    Could not find module ‘Termonad.Config.Colour’
    Use -v to see a list of the files searched for.
   |
21 | import           Termonad.Config.Colour         ( AlphaColour
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...


```

--- 

The first one looks like there's a version mismatch. The second one, however, is more confusing to me. 

Am I missing something here?
I've added haskellPackages.termonad to my configuration.nix file, and to test things out, I simply copy-pasted the example configuration in the readme.

**Comment by cdepillabout** [comment]
@asheshambasta Sorry you're having trouble with this.  Let me try to explain the two problems you're running into.

> When I add: termonad-with-packages

The problem here is that the version of Termonad from whatever nixpkgs you're using is too old.

The API exposed by Termonad often changes with major releases.  For instance, the API for termonad-2.0.0.0 is different from termonad-1.2.0.0.  If you install termonad-1.2.0.0 locally, but try to use the examples from the current README in this repo (which is for termonad-2.0.0.0), you will get the error you're seeing.

It looks like currently NixOS-19.03 has termoand-1.1.0.0, and NixOS-19.09 has termonad-2.0.0.0:

```console
$ nix-instantiate 'https://github.com/NixOS/nixpkgs-channels/archive/nixos-19.03.tar.gz' -A haskellPackages.termonad
/nix/store/58vg2lzjm2lyj0gz6wqm1lf8dvx7i39k-termonad-1.1.0.0.drv
$ nix-instantiate 'https://github.com/NixOS/nixpkgs-channels/archive/nixos-19.09.tar.gz' -A haskellPackages.termonad
/nix/store/wkbp5yh1bjfm19n3r2xwd5fy79zl61ab-termonad-2.0.0.0.drv
```

If you want to use termonad from nixos-19.03, I'd recommend looking for the README for termonad from the 1.1.0.0.

If you instead want to upgrade to nixos-19.09, you should get termonad-2.0.0.0, which is the current released version.  The config file in the current README should work.

-------------------------------------------------------------------------------

Your second problem is with the difference between `haskellPackages.termonad` vs. the top-level `termonad-with-packages`.

`haskellPackages.termonad` is purely the `termonad` binary.  It doesn't know how to find GHC, and doesn't know how to recompile your `~/.config/termonad/termonad.hs` file:

```console
$ nix-build '<nixpkgs>' -A haskellPackages.termonad
...
/nix/store/kl15ns49pwkswhkn37kk9bzpm1q0ha5d-termonad-2.0.0.0
$ file /nix/store/kl15ns49pwkswhkn37kk9bzpm1q0ha5d-termonad-2.0.0.0/bin/termonad
/nix/store/kl15ns49pwkswhkn37kk9bzpm1q0ha5d-termonad-2.0.0.0/bin/termonad: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/kksyrix1bpklvgkmvngcv0q9nh8hn2fl-glibc-2.27/lib/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, stripped
```

If you run this, it will give errors like you saw above, because it can't find GHC:

```console
$ NIX_GHC= /nix/store/kl15ns49pwkswhkn37kk9bzpm1q0ha5d-termonad-2.0.0.0/bin/termonad
Configuration '/home/illabout/.config/termonad/termonad.hs' changed. Recompiling.
IO error occurred when trying to run termonad:
: runProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
Don't know how to recover.  Exiting.
```

(I _think_ this is happening because GHC can't be found, although the error message could probably look a lot better...)

Instead, you should always make sure to use `termonad-with-packages`, which is actually a wrapper around the `termonad` binary that makes sure to set the `PATH` correctly so `termonad` can find GHC:

```console
$ nix-build '<nixpkgs>' -A termonad-with-packages
...
/nix/store/7vlcdbx332avjfajnph5rm7p086zzfvw-termonad-with-packages-8.6.5
$ cat /nix/store/7vlcdbx332avjfajnph5rm7p086zzfvw-termonad-with-packages-8.6.5/bin/termonad 
#! /nix/store/ily14d68xl11cnbbkf9svwnzwsrrnzah-bash-4.4-p23/bin/bash -e
export NIX_GHC='/nix/store/8dcinybkx4rvwbnkksjf8x2708zcsdx4-ghc-8.6.5-with-packages/bin/ghc'
exec "/nix/store/8dcinybkx4rvwbnkksjf8x2708zcsdx4-ghc-8.6.5-with-packages/bin/termonad"  "${extraFlagsArray[@]}" "$@"
```

----------------------------------------------------------------------------------------------

I think the README should probably point this out.  Could you send a PR updating the README with a short explanation of what you found confusing?

**Comment by asheshambasta** [comment]
@cdepillabout thanks for the very detailed reply. That explains things clearly. But yes, I do agree that this needs to be added in the README. 

By the time I read your reply, I could add my custom nix derivation that overcame this issue; and it was rather simple: 

``` nix 

{ pkgs ? import <nixpkgs> {} }: 

import (pkgs.fetchFromGitHub { 
          owner = "cdepillabout";
          repo = "termonad"; 
          rev = "be7d8c622b0e0fbede743524176b4bd630d7a997"; 
          sha256 = "1glg3f5dpnpk1mmdba95dmw2vwf8v236hvlvg99q4whd37vha3iy";
        }) {}

```

And in my configuration.nix: (`head -n 30`): 

``` nix 
{ config, pkgs, lib, ... }:

let

  oldTarball =
    fetchTarball "https://nixos.org/channels/nixos-18.09/nixexprs.tar.xz";
  myPkgs = { 
    termonad = pkgs.callPackage ./myPkgs/termonad.nix {};
  }; 

in {
  imports = [ # Include the results of the hardware scan.
    ./hardware-configuration.nix
  ];
... etc. 
``` 

To pin it to a given commit. 

That works for me, and the build takes a while, but yeah. 

This is well suited for someone not willing to `nix-env -i ...` to install packages but have it defined centrally. 

I can add these instructions to the README and open a PR if you're ok with that.

**Comment by cdepillabout** [comment]
@asheshambasta Thanks!  Please do!

**Comment by asheshambasta** [comment]
@cdepillabout I've not been able to look into this since I'm on a vacation. Its on my todo list as soon as I'm back. 
Sorry about the delay.

**Comment by cdepillabout** [comment]
Closing this since I think this info should already be in the README, but please feel free to send a PR improving things if the current README is not adequate.
