### ISSUE TITLE
Alias color for colour

### ISSUE THREAD

**Issue by toastal** [cdepillabout/termonad#139]
Given the nature of English's spelling controversies and other application configurations and things like CSS, VIM, et.al. only supporting `color`, it seems odd to not have an alias for the popular alternative spelling.

When I look at the issue titles in this project being split on the spelling, it seems an obvious way to prevent mistakes that people would expect to work.

**Comment by cdepillabout** [comment]
@toastal Thanks for this suggestion.

I originally went with `colour` instead of `color` because Termonad is using the [colour](http://hackage.haskell.org/package/colour) library (which goes with the `colour` spelling).

Since we directly re-export the `Colour` type defined in `colour`, I decided on using the `colour` spelling everywhere in the code.  (Any uses of the `color` spelling in function names or data types should be considered a bug.)

However, I'm from the US, so I'm more used to the `color` spelling, which is why you see it in issues, PRs, etc.

Since Termonad is directly exporting types from [colour](http://hackage.haskell.org/package/colour), the only way I'd be willing to define aliases in the Termonad code base is if you (or someone else) would be willing to create a wrapper library for [colour](http://hackage.haskell.org/package/colour) that exposed everything from that library plus aliases.

**Comment by toastal** [comment]
That makes a lot more sense. There's even a squabble in the title "colour: A model for human colour/color perception".

**Comment by cdepillabout** [comment]
I'm going to go ahead and close this, because it is relatively minor.

But if anyone is annoyed enough to pick this up, please feel free to comment here and I could re-open this issue.
