### ISSUE TITLE
Support for OSC1337 or SIXEL to show graphics

### ISSUE THREAD

**Issue by junjihashimoto** [cdepillabout/termonad#151]
It would be nice to support OSC1337 or SIXEL and be able to display graphics.

https://chromium.googlesource.com/apps/libapps/+/master/hterm/doc/ControlSequences.md#OSC-1337
https://en.wikipedia.org/wiki/Sixel

**Comment by cdepillabout** [comment]
Termonad is just using [VTE](https://wiki.gnome.org/Apps/Terminal/VTE) for the actual terminal emulator, so support for OSC1337 or SIXEL would have to be added to VTE first.

It looks like there has been some activity recently on a VTE bug about adding support for SIXEL: https://bugzilla.gnome.org/show_bug.cgi?id=729204

**Comment by junjihashimoto** [comment]
Thank you for sharing current status.

**Comment by cdepillabout** [comment]
It looks like there has been some work on sixel support in VTE over the last couple months: https://gitlab.gnome.org/GNOME/vte/-/issues/253 (and other related issues: https://gitlab.gnome.org/GNOME/vte/-/issues?scope=all&utf8=%E2%9C%93&state=opened&search=sixel)

I haven't really looked into this, but my guess is that in order to get this working, all you'd have to do is build VTE from the `master` branch.

If there needs to be something done in Termonad to enable sixel support, I'd be happy to merge in any PRs.

**Comment by cdepillabout** [comment]
I happened to be looking through the `gi-vte` documentation, and it appears that there is now SIXEL support: https://hackage.haskell.org/package/gi-vte-2.91.29/docs/GI-Vte-Objects-Terminal.html#g:attr:enableSixel

**Comment by cdepillabout** [comment]
This was implemented by @junjihashimoto in https://github.com/cdepillabout/termonad/pull/219, although we're still trying to figure out how well SIXEL is actually supported by VTE.  See that PR for the conversation.
