### ISSUE TITLE
Port termonad to Guix System

### ISSUE THREAD

**Issue by c4dr01d** [cdepillabout/termonad#168]
Hi, I'm a user of NixOS and Guix System. After I used termonad on NixOS, I think that termonad is the most suitable terminal for me. I want to use termonad on Guix System. I don't know termonad can be transplant to Guix System. It's possible?

**Comment by cdepillabout** [comment]
Hi, since Termonad is usable from nixpkgs, it should also be usable from Guix.  However, I don't have any experience with Guix, so I'm not sure how to best support it.

I don't plan on adding Guix support directly to this repo, but please feel free to create an issue upstream in the Guix repository.  Termonad is pretty similar to XMonad, and I bet that Guix has support for XMonad.  The code should be pretty similar for supporting Termonad.
