### ISSUE TITLE
gi-gtk -> Monomer?

### ISSUE THREAD

**Issue by Icy-Thought** [cdepillabout/termonad#204]
I apologize for the late promised issue submission, have been very busy recently.

It's worth mentioning that I am very new to the haskell world and thus this proposal should be taken with a grain of salt considering my very limited haskell knowledge. 😊

I recently came across a relatively new haskell native GUI library so called [Monomer](https://github.com/fjvallarino/monomer) and thought I should propose it to termonad as a possible replacement for the current gi-gtk implementation. 

Do share your thoughts about my proposal so I can learn from more experience haskell developers!

**Comment by cdepillabout** [comment]
I took a look at Monomer.  It looks pretty neat.

Although about 90% or so of the Termonad code-base is just GTK/VTE-related, so switching to use a different GUI library would effectively mean a complete rewrite!  I imagine it would be better to do this in a separate project.

The other question is if you decided to write a full terminal emulator program using a separate Haskell GUI library, what would you use for the actual terminal emulator?  Re-implementing an actual terminal emulator might be quite a lot of work.  (It would be neat to have a terminal emulator implemented fully in Haskell, though.)

I'm going to go ahead and close this, since it is unlikely that Termonad would switch to a separate GUI library.  Although I think this would be a neat project and I'd be happy if someone took this on!

**Comment by cdepillabout** [comment]
Also, from a brief read-through, it looks like Monomer promises an Elm-like architecture.  I think this is similar to the functionality provided by gi-gtk-declarative: https://github.com/cdepillabout/termonad/issues/79
