### ISSUE TITLE
updates on development

### ISSUE THREAD

**Issue by cdepillabout** [cdepillabout/termonad#63]
@LSLeary 

I just wanted to give you an update of what I'm working on.

I'm thinking about removing the Monoid and Semigroup instances for `ConfigHooks`.  While I think there are a lot of good reasons to have a `Monoid` instance for `ConfigHooks` (mostly that it makes combining them more principled), I think it gives us a little more indirection about updating hooks.  I'm in the process of changing around how some of the extension stuff works.  I'll send a PR when I have it working.

At some point in the future we may want to move back to the `ConfigHooks` and `ConfigExtension` combination.

Also, I don't think we should depend on the `type-combinators` library, mostly because your two PRs haven't been touched yet.  I plan on moving all of the `Vec` stuff we're using directly into termonad for now (but hopefully at some point pushing it out into a third-party library).  If you wanted to go ahead and do this, please feel free.  I'll probably start working on it after I send my next PR concerning the `ConfigHooks` and `ConfigExtension` stuff.

(As an aside, I also hope to do this for the `FocusList` module.)

**Comment by cdepillabout** [comment]
The small amount of work I have so far is on the `update-extensions` branch.

**Comment by cdepillabout** [comment]
I've been thinking about the extension stuff for the last couple days.

Here are my thoughts:

Essentially, the extensions are a tuple of three things:

1. A way to hook into existing Termonad functionality.  These are represented as hooks exposed by Termonad.  An example of this is the `createTermHook`.  This is currently done with the `ConfigExtension` type class and the `hooks` method.
2. A way to manage some sort of state.  The current extensions need a way to manage their own state.  For example, the color extension has a `ColourConfig` as state.  It needs to manage this, as well as use it during the `createTermHook`.  Currently, the extension IS its own state.  The list of extensions is currently wrapped in an existential container (`SomeConfigExtension` and `Both`) so that multiple different config extensions can be kept together.
3. A way to expose its state to other extensions.  The `ColourConfig` should be able to be updated by other extensions.  This is currently done with the function `message`.  The `ColourConfig` is able to respond to arbitrary messages (but currently it only responds to the `UpdateColour` message).  These messages provide a way of mutating the existing `ColourConfig`.

Wrapping these three things together with the `ConfigExtension` type class gives us a principled way to work with extensions, but I'm worried that it is too principled for now.  I'm thinking of refactoring it to make it more flexible (and more manual?).

I'm thinking of changing it so that each extension will just be a datatype that exposes the hooks it needs as well as its internal state wrapped in an `MVar` so it can be shared with other extensions.  The user will then need to manually hookup the hooks, as well as pass the internal state to other extensions as needed.  Of course, helper functions can be provided to make this easier.

I'll send a PR implementing the basic idea of this.

Although, don't get me wrong, I'm not sure if this "unprincipled" approach would be better in the long run.  I think it might make it more flexible for the first couple extensions, but I may regret this decision later if the extensions become a tangled mess.

**Comment by LSLeary** [comment]
I have big problems with the changes to the extension system.

### User Interface
This was probably my core focus in the original implementation. Being able to import a record type holding new configuration options and simply "add" them to your existing ones is very nice, and should not be sacrificed without a very good reason. It's hard to say that the ad hoc approach has a user interface, and since the extensions themselves lack a regular structure I don't see one being written on top of it.

### Public Mutable State
As an extension author I do want to be able to expose my state, but I also need to set some conditions on that. Perhaps my types are not strong enough to ensure that all possible values of my state are valid. Perhaps (and this is *very* likely) my state needs to be kept consistent with the world, requiring me to handle changes when they're made. Using messages instead of handing out an `MVar` ensures that I mediate all changes, allowing me to maintain whatever properties I need to, and rest easy in the fact that *my state is how I left it*. That kind of assurance is one of the reasons people write Haskell in the first place.

### The Pros
What is the newfound flexibility that cannot be expressed within or on top of the `ConfigExtension` framework? I don't really see what we've gained.

If two extensions really want to offer and accept `MVar`s for each other's state they can do so as options. If an extension really wants its hooks to be combined-in non-monoidally it can provide a combinator other than `Both`. If an extension really wants to expose its state for reading/use it can implement a message `ReadMyState (MyState -> IO ())`. Et cetera. What is the restriction that needs to be lifted?

The design of the messaging system does have one clear weakness/restriction as it stands, in that state manipulating messages do not compose. But there are several ways to improve/fix that without needing to strip out the whole system.

**Comment by cdepillabout** [comment]
Since this was originally just an update on development, I'm going to go ahead and close it.  Although free free to re-open it or post a new issue.
