### ISSUE TITLE
Background Highlights Not Working in Vim

### ISSUE THREAD

**Issue by craigem** [cdepillabout/termonad#89]
Thanks for this project. Greatly appreciated and timely (for me).

I've been developing a Solarized colour scheme for Termonad and in that process I noticed in either my colour scheme, the default colour scheme or the [example colour scheme](https://github.com/cdepillabout/termonad/blob/master/example-config/ExampleColourExtension.hs#L37-L7) that background highlights were not working in ViM.

They ought to appear, colour scheme depending, something like this:

https://raw.githubusercontent.com/altercation/solarized/master/img/screen-haskell-dark.png

Note the background of the status bar at the bottom and the number colour column. Those background highlights are what appear to be missing in Termonad.

I've been unable to resolve it thus far. 

Is this issue happening for other uses or is there perhaps an issue on my end only?

**Comment by cdepillabout** [comment]
Hi @craigem, sorry to hear you're having problems with color-stuff.  Let's see if we can figure it out.

So, to start off with, the ansi color stuff for terminals is pretty complicated:

https://en.wikipedia.org/wiki/ANSI_escape_code#Colors

And then VTE's interface on top of that is also somewhat weird.  I've tried to explain how it works in the Termonad haddocks, but the explanation is quite long:

http://hackage.haskell.org/package/termonad-1.0.1.0/docs/Termonad-Config-Colour.html

Here's some things you could do to try to debug this:

1. Post your Haskell code that you're using to set the colors for Termonad.

2. Post your `TERM` environment variable that is set when running the terminal.

    As a reference, here's mine:

    ```sh
    $ echo $TERM
    xterm-256color
    ```

3. Try running one of those programs that print all 256 ansi colors and post the results here.

    For a reference, here is the output of running [this](https://askubuntu.com/a/821163) in my terminal:

    ![terminal-colors](https://user-images.githubusercontent.com/64804/49551736-c515f900-f933-11e8-8e6f-96db1c1d00eb.png)

4. Try to figure out how Vim translates its colors to the ansi escape sequences, so that you can be sure you're setting the right one.

**Comment by craigem** [comment]
Thanks to @LSLeary on #termonad, this has been resolved. 

It turned out to be a vim.rc configuration issue, rather than Termonad itself. 

Although other terminals (in particular Terminology, lxterminal, gnome-terminal) displayed the background highlights correctly, Termonad required me to clear a whole swag of existing settings and enable the Solarized toggle for ViM.

I don't consider this a Termonad issue at all anymore but some weird intersection of how other terminals implement their palettes and my ViM settings.

I've almost got it all resolved now and once I'm happy that my implementation of the Solarized pallete is correct, expect a pull request for another colour config example.

Thanks!

:-D

**Comment by craigem** [comment]
When I first had a crack at Solarizing Termonad, I could not figure out how to do more than 8 colours. Not being able to have a solarized terminal made it initially unusable. 

@LSLeary pointed out your recent Vec example, so using that I was able to achieve what I wanted, once I'd sorted the Termonad colour configuration issues from the local (ViM) issues.

Pretty happy.

Pull request coming shortly.
